### ISSUE TITLE
The errors reported during the test are as follows

### ISSUE THREAD

**Issue by bukeyan4318** [dlinzhao/JSNet#14]
hello,I successfully trained my data set. My dataset has only 2 categories. I tried to modify the code and changed 13 to 2. The errors reported during the test are as follows. What's the problem?
f = h5py.File(filename)
Traceback (most recent call last):
  File "test.py", line 281, in <module>
    test()
  File "test.py", line 159, in test
    cur_pred_sem_softmax = np.zeros([cur_sem.shape[0], cur_sem.shape[1], NUM_CLASSES])
IndexError: tuple index out of range
I look forward to your reply very much, and I will be very grateful!!!

**Comment by dlinzhao** [comment]
@bukeyan4318 It seems that the data does not be loaded correctly. You could try to set the command line parameter `--data_type` to `numpy`.

**Comment by bukeyan4318** [comment]
@dlinzhao hello ,I've tried to change the -- data_ type to numpy, and the error content is consistent with HDF5. What should I do?

**Comment by dlinzhao** [comment]
@bukeyan4318 You can print some log information to see the data is loaded correctly. I would like to suggest you debug the program step-by-step to make sure the data is loaded correctly.

**Comment by bukeyan4318** [comment]
@dlinzhao hello ,but When i use your code to generate .npy and .h5 files, the code does not report an error。Can you explain that there is no problem with my dataset production?

**Comment by dlinzhao** [comment]
@bukeyan4318 It seems that your data only contains a block in some files, which causes the operation `np.squeeze(cur_sem)` to remove all dimensions but the points.

You can add the operation `print('cur_sem shape: ', cur_sem.shape)` before line 148 and 158 to see the variation of `cur_sem`.  The log information maybe like this:
```
cur_sem: (B, N)
cur_sem: (N)
```

If this is the case, you could modify or commit the following two lines: 
```
cur_sem = np.squeeze(cur_sem)
cur_group = np.squeeze(cur_group)
```
to
```
cur_sem = np.reshape(cur_sem, [cur_data.shape[0], cur_data.shape[1]])
cur_group = np.reshape(cur_group , [cur_data.shape[0], cur_data.shape[1]])
```

**Comment by bukeyan4318** [comment]
@dlinzhao The problem has been solved. Thank you very much. I can't restrain my emotions now. I'm very happy. Again, thank you!!!
