### ISSUE TITLE
How to make the coordinate system in the test generation visualization file the same as that in the data set?

### ISSUE THREAD

**Issue by bukeyan4318** [dlinzhao/JSNet#15]
Hello，Your work is excellent.I found that the coordinate system in the visual file generated by the test is different from that in the data set. I want the two coordinate systems to be the same. How can I operate? Your answer is very important to me. I look forward to your reply.It's important to me. Thank you in advance.

**Comment by dlinzhao** [comment]
@bukeyan4318 you can reference the answer in #5.

**Comment by bukeyan4318** [comment]
@dlinzhao hello,In other words,How to make the XYZ coordinate system generated by the test consistent with the XYZ coordinate system in the original data set ? The XYZ coordinate system generated by the test is not based on the original data set.I look forward to your reply.It's important to me. Thank you in advance.

**Comment by dlinzhao** [comment]
@bukeyan4318 At the preprocessing, the coordinate xyz will subtract its minimum. So, you can add the minimum from original data to the coordinate of test results. Please reference the [preprocessing](https://github.com/dlinzhao/JSNet/blob/master/utils/indoor3d_util.py#L69).

**Comment by bukeyan4318** [comment]
@dlinzhao Thank you very much. I understand. However, what makes me curious is why the XYZ coordinate should subtract its minimum value. I tried not to subtract the minimum value before retraining, and the code operation reported an error. I wonder why the minimum should be subtracted?

**Comment by dlinzhao** [comment]
@bukeyan4318 Because the input data will be split into multi-blocks, you can refer to [room2blocks](https://github.com/dlinzhao/JSNet/blob/master/utils/indoor3d_util.py#L206).

**Comment by bukeyan4318** [comment]
@dlinzhao Thank you very much for your patient answer. Thank you sincerely!
