### ISSUE TITLE
Wrong test results

### ISSUE THREAD

**Issue by LaureenK** [dlinzhao/JSNet#16]
Hi, thanks for your code. I tested the JSNet with my own data created from a Dynamic Vision Sensor. I get some weird test results, as you can see from the image. The Bounding Boxes are the instances, and the colors are the different semantic classes. Is it possible, like for instance 2, that points from different semantic classes are clustered to one instance? Moreover, I don’t understand why instance 1 has some points from instance 4 even if there is a huge space between them. Do you know any reason why this could happen? Did I miss something while clustering?
Thanks for your help!
![0](https://user-images.githubusercontent.com/32844590/152138837-8ec5385c-35f0-47fe-a2d0-4b774b3b1013.png)

**Comment by dlinzhao** [comment]
@LaureenK This is very strange, you can try using the `test.py` to generate the obj file and visualize it with MeshLab.
