### ISSUE TITLE
About version of TensorFlow

### ISSUE THREAD

**Issue by zhangguanghui1** [dlinzhao/JSNet#2]
Could you tell me what your version of TensorFlow  is?

**Comment by dlinzhao** [comment]
@zhangguanghui1 Thank you for your attention, we use the Tensorflow 1.4 or Tensorflow 1.7.

**Comment by zhangguanghui1** [comment]
@dlinzhao Thank you very much!

**Comment by brianlen** [comment]
@dlinzhao Is TensorFlow 1.4.1 okay?

**Comment by dlinzhao** [comment]
It works well with Tensorflow 1.4 or Tensorflow 1.7. You can re-compile the tensorflow operation under the folder `tf_ops` and then test it.

**Comment by dlinzhao** [comment]
> @dlinzhao Is TensorFlow 1.4.1 okay?

It works well with Tensorflow 1.4 or Tensorflow 1.7. You can re-compile the tensorflow operation under the folder tf_ops and then test it.
