### ISSUE TITLE
Unable to train successfully

### ISSUE THREAD

**Issue by camelliawb** [dlinzhao/JSNet#3]
Thank you for your sharing of the codes.But when I run train.py,I got problem that the program was running all the time.I found the program maybe stuck in this sentence：
    for batch_idx in range(num_batches):
        print('here5--------------')
        current_data, current_sem, current_label = dataset.get_batch(False) 
Have you any idea for why could this be happening?Look forward to your reply.

**Comment by dlinzhao** [comment]
You can stop the program manually or rewrite the function `def __del__(self)` in `utils/s3dis_utils/dataset_s3dis.py` as follows:
``` python
def __del__(self):
    try:
        self.consumer_process.kill()
        self.producer_process.kill()
    except:
        pass
```
