### ISSUE TITLE
How to train the model on ShapeNet

### ISSUE THREAD

**Issue by Chenfeng1271** [dlinzhao/JSNet#6]
Thanks for your sharing. I have trained the code on S3DIS very well, but I don't know how to train it on ShapeNet as the paper. Cou you give me some advice?

**Comment by Hiram9270** [comment]
@Chenfeng1271 I am training the code on S3DIS,but I don't know which directory to put the dataset in, I put it under the data folder, running the "python utils/s3dis_utils/collect_indoor3d_data.py" command when there was an error, it seems that it can not find where the dataset is, which makes me crazy, I hope you can help me, thank you.

**Comment by dlinzhao** [comment]
@MrNeoJeep The dataset can be saved in other folders. Then, you can create some soft-links in `data` folder, e.g.,
```bash
cd data
ln -s path_to_dataset Stanford3dDataset_v1.2_Aligned_Version
mkdir -p path_to_output_folder
ln -s path_to_output_folder stanford_indoor3d_ins.sem
```

**Comment by dlinzhao** [comment]
@Chenfeng1271 For the ShapeNet dataset, the DBScan clustering (e.g., sklearn API) is used to generate the instance annotations. Then, you should adjust some parameters (e.g., num_points, num_classes). Afterwards, you can train the model on the ShapeNet dataset like S3DIS.
