### ISSUE TITLE
tf_sampling_so.so not found during train.py

### ISSUE THREAD

**Issue by brianlen** [dlinzhao/JSNet#8]
@dlinzhao When I run train.py, I get a error "tf_sampling_so.so not found". But I see the file in /tf_ops/sampling/tf_sampling_so.so. Why does train.py cannot find the file?

Do you know how to fix this?

**Comment by dlinzhao** [comment]
You can try to set environment variable` PYTHONPATH=/path/JSNet:$PYTHONPATH` in  Bash Shell or your IDE.
